import 'package:flutter/material.dart';
import '../../services/trusted_contact_service.dart';

class TrustedContactsScreen extends StatefulWidget { const TrustedContactsScreen({super.key}); @override State<TrustedContactsScreen> createState() => _TrustedContactsScreenState(); }
class _TrustedContactsScreenState extends State<TrustedContactsScreen> {
  final _service = TrustedContactService(); List<Map<String, dynamic>> _items = []; bool _loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { try { _items = await _service.list(); } catch (_) { _message('Impossible de charger les contacts.'); } finally { if (mounted) setState(() => _loading = false); } }
  Future<void> _add() async { final name = TextEditingController(); final phone = TextEditingController(); final relation = TextEditingController(); final ok = await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: const Text('Ajouter un contact'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Nom')), TextField(controller: phone, decoration: const InputDecoration(labelText: 'Téléphone'), keyboardType: TextInputType.phone), TextField(controller: relation, decoration: const InputDecoration(labelText: 'Relation'))]), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Annuler')), FilledButton(onPressed: () async { if (name.text.trim().isEmpty || phone.text.trim().isEmpty) return; try { await _service.create(name: name.text, phone: phone.text, relationship: relation.text); if (context.mounted) Navigator.pop(context, true); } catch (_) { _message('Ajout impossible.'); } }, child: const Text('Ajouter'))])); name.dispose(); phone.dispose(); relation.dispose(); if (ok == true) { setState(() => _loading = true); await _load(); } }
  Future<void> _remove(String id) async { try { await _service.remove(id); await _load(); } catch (_) { _message('Suppression impossible.'); } }
  void _message(String value) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(value))); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Contacts de confiance'), actions: [IconButton(onPressed: _add, icon: const Icon(Icons.add))]), body: _loading ? const Center(child: CircularProgressIndicator()) : _items.isEmpty ? const Center(child: Text('Aucun contact enregistré.')) : ListView.builder(itemCount: _items.length, itemBuilder: (_, i) { final item = _items[i]; return ListTile(leading: const CircleAvatar(child: Icon(Icons.person)), title: Text('${item['name']}'), subtitle: Text('${item['phone']}'), trailing: IconButton(icon: const Icon(Icons.delete_outline), onPressed: () => _remove('${item['id']}'))); }));
}
