import 'package:flutter/material.dart';
import '../../services/sos_service.dart';

class SosScreen extends StatefulWidget { const SosScreen({super.key}); @override State<SosScreen> createState() => _SosScreenState(); }
class _SosScreenState extends State<SosScreen> {
  final _service = SosService(); final _message = TextEditingController(); bool _loading = false;
  @override void dispose() { _message.dispose(); super.dispose(); }
  Future<void> _trigger() async { final confirm = await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: const Text('Déclencher SOS ?'), content: const Text('L’alerte sera enregistrée. Contactez aussi les services d’urgence si nécessaire.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Annuler')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Déclencher'))])); if (confirm != true) return; setState(() => _loading = true); try { await _service.trigger(message: _message.text); if (mounted) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Alerte SOS enregistrée.'))); Navigator.pop(context); } } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Envoi impossible.'))); } finally { if (mounted) setState(() => _loading = false); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Alerte SOS')), body: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Icon(Icons.warning_amber_rounded, size: 80, color: Colors.red), const SizedBox(height: 20), const Text('En cas de danger immédiat, contactez les services d’urgence locaux.', textAlign: TextAlign.center), const SizedBox(height: 20), TextField(controller: _message, maxLines: 3, decoration: const InputDecoration(labelText: 'Message optionnel')), const Spacer(), FilledButton(onPressed: _loading ? null : _trigger, style: FilledButton.styleFrom(backgroundColor: Colors.red.shade700, foregroundColor: Colors.white), child: Text(_loading ? 'Envoi...' : 'DÉCLENCHER SOS'))]));
}
